# Generated by Django 4.0.6 on 2022-07-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='upload',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
